name: Build Kernel strawing
run-name: Build Kernel strawing with KernelSU Next susfs
on:
  workflow_dispatch:
jobs:
  build_job:
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CI: "false"
    steps:

      - name: 1.拉取编译链
        run: |
          mkdir $GITHUB_WORKSPACE/proton-clang
          cd proton-clang
          wget https://github.com/kdrag0n/proton-clang/archive/refs/tags/20210522.zip
          unzip 20210522.zip
          cd ..
          sudo apt install build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3

      - name: 2.拉取并编译
        run: |
          mkdir $GITHUB_WORKSPACE/kernel_workspace
          cd $GITHUB_WORKSPACE/kernel_workspace
          git clone https://github.com/clcwpwqi/kernel_865_mod -b android14-lineage21-mod --depth=1 android_kernel
          cd android_kernel
          bash build.sh umi ksu

      - name: 3.上传刷机包
        uses: actions/upload-artifact@v4
        with:
          name: KernelSU-Next-SUSFS-AnyKernel3
          path: kernel_workspace/android_kernel/anykernel*
          retention-days: 3
