name: Build Kernel ksn stawing
run-name: Build Kernel srw with KernelSU Next susfs
on:
  workflow_dispatch:
    inputs:
      phone:
        description: '选择手机型号：'
        required: true
        default: 'umi'
        type: choice
        options:
          - umi
          - cmi
      susfs:
        description: '是否集成SUSFS：'
        required: true
        default: 'SUSFS'
        type: choice
        options:
          - SUSFS
          - NoSUSFS
      version:
        description: '自定义版本名（如perf-xxx）可为空（则为n0kernel）'
        required: false
        type: string
jobs:
  build_job:
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CI: "false"
    steps:

      - name: 1.拉取编译链
        run: |
          mkdir $GITHUB_WORKSPACE/proton-clang
          cd proton-clang
          wget https://github.com/kdrag0n/proton-clang/archive/refs/tags/20210522.zip
          unzip 20210522.zip
          cd ..
          sudo apt install build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python

      - name: 2.拉取源码与补丁
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          git clone https://github.com/clcwpwqi/kernel_865_mod -b android14-lineage21-mod --depth=1 android_kernel
          git clone https://github.com/clcwpwqi/kernel.git src
          cd android_kernel
          bash build.sh umi ksu

      - name: 8.上传刷机包
        uses: actions/upload-artifact@v4
        with:
          name: KernelSU-Next-AnyKernel3
          path: kernel_workspace/android_kernel/anykernel*
          retention-days: 3
